identifier_name:
  excluded:
    - id
    - to
    - ms
    - pa
    - i
    - j
    - k
    - x
    - y
    - z

disabled_rules:
  - multiple_closures_with_trailing_closure
  - no_space_in_method_call
  - redundant_string_enum_value
  - nesting
  - switch_case_alignment
  - unused_capture_list

line_length:
  warning: 120
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true
  
opt_in_rules:
  - deployment_target
  - force_unwrapping
  - redundant_type_annotation
  - force_try
  - operator_usage_whitespace

deployment_target:
    iOSApplicationExtension_deployment_target:      "${deployment_target_iOS}"
    iOS_deployment_target:                          "${deployment_target_iOS}"
    macOSApplicationExtension_deployment_target:    "${deployment_target_macOS}"
    macOS_deployment_target:                        "${deployment_target_macOS}"
    tvOSApplicationExtension_deployment_target:     "${deployment_target_tvOS}"
    tvOS_deployment_target:                         "${deployment_target_tvOS}"
    watchOSApplicationExtension_deployment_target:  "${deployment_target_watchOS}"
    watchOS_deployment_target:                      "${deployment_target_watchOS}"
