name: iOS UITest Workflow
on:
  push:
    branches:
      - main
      - "*"
  pull_request:
    branches:
      - main
      - "*"
jobs:
  build:
    name: Build and Test UnitTests using iPhone 15 Pro Max simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and test ( iOS 16.0)
        run: xcodebuild clean test -testPlan UITests -project "Sensor-App.xcodeproj" -scheme "Sensor-App" -destination "platform=iOS Simulator,name=iPhone 15 Pro Max,OS=latest"
