name: Lint Code

on:
  push:
    branches:
      - main
      - "*"
  pull_request:
    branches:
      - main
      - "*"
    paths:
      - ".github/workflows/codelint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint code using SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
